# <span style="color:#0b486b">SIT 112 - Data Science Concepts</span>

---
Lecturer: Truyen Tran | truyen.tran@deakin.edu.au<br />


School of Information Technology, <br />
Deakin University, VIC 3215, Australia.

---

## <span style="color:#0b486b">Practical Session 4: Skills you need to deal with the data</span>

**The purpose of this session is to teach you:**

* Become familiar with numpy package
* Become familiar with matplotlib pasckage
* Gain an understanding of the availability of data sources: rss feed, public data domain
* Be able to: load, .xls, .csv and .json and export them into different data format
* Plot a histogram and a boxplot
---

## <span style="color:#0b486b">1. Numpy</span>


Python lists are very flexible for storing any sequence of Python objects. But usually flexibility comes at the price of performance and therefore Python lists are not ideal for numerical calculations where we are interested in performance. Here is where **NumPy** comes in. It adds support for large, multi-dimensional arrays and matrices, along with high-level mathematical functions to operate on these arrays to Python. 

Relying on `'BLAS'` and `'LAPACK'`, `'NumPy'` gives a functionality comparable with `'MATLAB'` to Python. NumPy facilitates advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences. It has become one of the fundamental packages used for numerical computations.

In this tutorial we will review its basics, so to learn more about NumPy, visit [NumPy User Guide](http://docs.scipy.org/doc/numpy/user/index.html)

### <span style="color:#0b486b">1.1 Importing Numpy</span>

As you have learnt in tutorial 2, first we have to import a package to be able to use it. NumPy is imported with:

In [1]:
import numpy

It is the convention to import it like with an alias:

In [2]:
import numpy as np

### <span style="color:#0b486b">1.2 Numpy arrays</span>

The core of NumPy is its arrays. You can create an array from a Python list or tuple using `'array'` function. They work similarly to lists apart from the fact that:

* you can easily perform element-wise operation on them, and
* unlike lists, they should be pre-allocated.

The first point is further explained in [Array operations section](2-prac4.ipynb#1.4-Array-operations). The second point means that you there is no equivalent to list append for arrays. The size of the arrays is known at the time it is defined.

#### <span style="color:#0b486b">1.2.1 create an array from a list</span>

In [3]:
x = [1, 7, 3, 4, 0, -5]


In [9]:
y = np.array(x)
type(y)

numpy.ndarray

#### <span style="color:#0b486b">1.2.2 create an array using a range</span>

In [4]:
range(5)

range(0, 5)

In [7]:
print(np.array(range(5)))

[0 1 2 3 4]


In [8]:
print(np.arange(2, 3, 0.2))

[2.  2.2 2.4 2.6 2.8]


In [9]:
# returns numbers spaced evenly on a linear scale, both endpoints are included
# (2, 3, 5): two endpoints are 2 & 3 and there're 5 numbers in the array.
print(np.linspace(2, 3, 5))

[2.   2.25 2.5  2.75 3.  ]


In [10]:
print(np.logspace(2, 3, 5))    # returns numbers spaced evenly on a log scale

[ 100.          177.827941    316.22776602  562.34132519 1000.        ]


**Note:** If you need any help on how to use a function or what it does, you can use IPython help. Just add a question mark (?) at the end of the function and execute the cell:

In [12]:
np.logspace?

#### <span style="color:#0b486b">1.2.3 create a prefilled array</span>

In [13]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [14]:
print(np.ones(5, dtype=int))    # you can specify the data type, default is float

[1 1 1 1 1]


#### <span style="color:#0b486b">1.2.4 `'mgrid'`</span>
similar to meshgrid in MATLAB:

In [19]:
x, y = np.mgrid[0:5, 0:3]

print(x)
print(y)
np.mgrid?

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]


#### <span style="color:#0b486b">1.2.5 array attributes</span>
NumPy arrays have multiple attributes and methods. The cell below shows a few of them. You can press tab after typeing the dot operator `'(.)'` to use IPython auto-complete and see the rest of them.

In [16]:
y = np.array([3, 0, -4, 6, 12, 2])

In [17]:
print("number of dimensions:\t", y.ndim)
print("dimension of the array:", y.shape)       
print("numerical data type:\t", y.dtype)
print("maximum of the array:\t", y.max())       
print("index of the array max:", y.argmax())
print("mean of the array:\t", y.mean())

number of dimensions:	 1
dimension of the array: (6,)
numerical data type:	 int32
maximum of the array:	 12
index of the array max: 4
mean of the array:	 3.1666666666666665


#### <span style="color:#0b486b">1.2.6 Multi-dimensional arrays</span>


You can define arrays with 2 (or higher) dimensions in numpy:

##### from lists

In [21]:
x = [[1, 2, 10, 20], [3, 4, 30, 40]]
y = np.array(x)
print(y)
print()
print(y.ndim, y.shape)
np.shape?

[[ 1  2 10 20]
 [ 3  4 30 40]]

2 (2, 4)


##### pre-filled 

In [22]:
x = np.ones((3, 5), dtype='int')

In [23]:
print(x)
print()
print(x.ndim, x.shape)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

2 (3, 5)


##### `'diag()'`
diagonal matrix

In [24]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [25]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### <span style="color:#0b486b">1.3 Manipulating arrays</span>


#### <span style="color:#0b486b">1.3.1 Indexing</span>


Similar to lists, you can index elements in an array using `'[]'` and indices:

If `'x'` is a 1-dimensional array, `'x[i]'` will index `'ith'` element of `'x'`:

In [26]:
x = np.array([2, 8, -2, 4, 3])
print(x[3])

4


If 'x' is a 2-dimensional arrray:

* '`x[i, j]'` or `'x[i][j]'` will index the element in `'ith'` row and `'jth'` column
* '`x[i, :]'` will index the `'ith'` row 
* `'x[:, j]'` will index `'jth'` column

In [27]:
x = np.array([[7, 6, 8, 6, 4],
              [4, 7, -2, 0, 9]])
              
print(x[1, 3])

0


In [28]:
print(x[1, :])      # or x[1]

[ 4  7 -2  0  9]


In [29]:
print(x[:, 3])

[6 0]


Arrays can also be indexed with other arrays:

In [30]:
x = np.array([2, 8, -2, 4, 3, 9, 0])

idx1 = [1, 3, 4]        # list
idx2 = np.array(idx1)   # array

print(x[idx1], x[idx2])
x[idx2] = 0
print(x)

[8 4 3] [8 4 3]
[ 2  0 -2  0  0  9  0]


You can also index masks. The index mask should be a NumPy arrays of data type Bool. Then the element of the array is selected only if the index mask at the position of the element is True.

In [31]:
x = np.array([2, 8, -2, 4, 3, 9, 0])

In [32]:
mask = np.array([False, True, True, False, False, True, False])

In [33]:
x[mask]

array([ 8, -2,  9])

Combining index masks with comparison operaors enabels you to conditinoally slecect elements of the array.

In [35]:
x = np.array([2, 8, -2, 4, 3, 9, 0])
mask = (x>=2) * (x<9) #first element = True * True = True (2 >= 2 * 2 < 9)
print(mask)
x[mask]

[ True  True False  True  True False False]


array([2, 8, 4, 3])

#### <span style="color:#0b486b">1.3.2 Slicing</span>


Similar to Python lists, arrays can also be sliced:

In [36]:
x = np.array([2, 8, -2, 4, 3, 9, 0])

print(x[3:])    # slicing
print(x[3:7:2])  # slicing with a specified step

[4 3 9 0]
[4 9]


In [37]:
x = np.array([[7, 6, 8, 6, 4, 3],
              [4, 7, 0, 5, 9, 5],
              [7, 3, 6, 3, 5, 1]])
              

print(x[1, 1:4])
print()
print(x[:2, 1::2])    # rows zero up to 3, cols 1 up to end with a step=2

[7 0 5]

[[6 6 3]
 [7 5 5]]


#### <span style="color:#0b486b">1.3.3 Iteration over items</span>


Since most of NumPy functions are capable of operating on arrays, in many cases iteration over items of an arrays can be (and should be) avoided. Otherwise it is pretty much similar to iterating over values of a list:

In [38]:
a = np.arange(0, 50, 7)
print(a)
for item in a:
    print(item, end=' ')

[ 0  7 14 21 28 35 42 49]
0 7 14 21 28 35 42 49 

Of course you could iterate over items using their indices too:

In [44]:
a = np.arange(0, 50, 7)
for i in range(a.shape[0]):
    print(a[i], end=' ')

print("\n", a.shape[0])

0 7 14 21 28 35 42 49 
 8


There are also many functions for manipulating arrays. The most used ones are:

#### 1.3.4 `copy()`

**Remember** that assignment operator is not an equivalent for copying arrays. In fact Python does not pass the values. It passess the references.

In [45]:
x = [1, 2, 3]
y = x
print(x, y)

[1, 2, 3] [1, 2, 3]


In [46]:
y[0] = 0       # now we alter an element of y
print(x, y)     # note that x has changed as well

[0, 2, 3] [0, 2, 3]


Same is true for numpy arrays. That's why if you need a copy of an array, you should use `'copy()'` function.

In [47]:
x = np.array([1, 2, 3])
y = x

y[0] = 0       # now we alter an element of y
print(x, y)     # note that x has changed as well

[0 2 3] [0 2 3]


In [48]:
x = np.array([1, 2, 3])
y = x.copy()  # or np.copy(x)
y[0] = 0

print(x, y)

[1 2 3] [0 2 3]


#### 1.3.5 `reshape()`

In [49]:
x1 = np.arange(6)
x2 = x1.reshape((2, 3))    # or np.reshape(x1, (2, 3))

print(x1)
print()
print(x2)


[0 1 2 3 4 5]

[[0 1 2]
 [3 4 5]]


#### 1.3.6 `astype()`

Used for type casting:

In [50]:
x1 = np.arange(5)
x2 = x1.astype(float)

print(type(x1), x1)
print(type(x2), x2)

<class 'numpy.ndarray'> [0 1 2 3 4]
<class 'numpy.ndarray'> [0. 1. 2. 3. 4.]


#### 1.3.7 `T`

transpose method:

In [55]:
x1 = np.random.randint(5, size=(2, 4))
x2 = x1.T

print(x1)
print()
print(x2)

np.random.randint?

[[3 2 4 2]
 [2 1 3 0]]

[[3 2]
 [2 1]
 [4 3]
 [2 0]]


### <span style="color:#0b486b">1.4 Array operations</span>


#### <span style="color:#0b486b">1.4.1 Arithmetic operators</span>


Arrays can be added, subtracted, multiplied and divided using +, -, \* and, /. Operations done by these operators are **element wise**.

In [56]:
x1 = np.array([[2, 3, 5, 7], 
               [2, 4, 6, 8]], dtype=float)
x2 = np.array([[6, 5, 4, 3], 
               [9, 7, 5, 3]], dtype=float)

print(x1)
print()
print(x2)

[[2. 3. 5. 7.]
 [2. 4. 6. 8.]]

[[6. 5. 4. 3.]
 [9. 7. 5. 3.]]


In [57]:
print(x1 + x2)

[[ 8.  8.  9. 10.]
 [11. 11. 11. 11.]]


In [58]:
print(x1 - x2)

[[-4. -2.  1.  4.]
 [-7. -3.  1.  5.]]


In [59]:
print(x1 * x2)

[[12. 15. 20. 21.]
 [18. 28. 30. 24.]]


In [60]:
print(x1 / x2)

[[0.33333333 0.6        1.25       2.33333333]
 [0.22222222 0.57142857 1.2        2.66666667]]


In [61]:
print(3 + x1)

[[ 5.  6.  8. 10.]
 [ 5.  7.  9. 11.]]


In [62]:
print(3 * x1)

[[ 6.  9. 15. 21.]
 [ 6. 12. 18. 24.]]


In [63]:
print(3 / x1)

[[1.5        1.         0.6        0.42857143]
 [1.5        0.75       0.5        0.375     ]]


#### <span style="color:#0b486b">1.4.2 Boolean operators</span>

Much like arethmaic operators discussed above, boolean (comparison) operatos perform element-wise on arrays.

In [64]:
x1 = np.array([2, 3, 5, 7])
x2 = np.array([2, 4, 6, 7])
y = x1<x2

print(y, y.dtype)

[False  True  True False] bool


use methods `'.any()'` and `'.all()'` to return a single boolean value indicating whether any or all values in the array are True respectively. This value in turn can be used as a condition for an `'if'` statement.

In [65]:
print(y.all())
print(y.any())

False
True


NumPy has many other functions that you can read about them in [NumPy User Guide](http://docs.scipy.org/doc/numpy/user/). Specially read about:

* `np.unique`, returns unique elements of an array
* `np.flatten`, flattens a multi-dimensional array
* `np.mean`, `np.std`, `np.median`
* `np.min`, `np.max`, `np.argmin`, `np.argmax`

### <span style="color:#0b486b">1.5 np.random</span>


NumPy has a module called `random` to generate arrays of random numbers. There are different ways to generate a random number:

In [66]:
print(np.random.rand())

0.9687042817579573


In [67]:
# 2x5 random array drawn from standard normal distribution
print(np.random.random([2, 5]))

[[0.33413708 0.69510482 0.10018648 0.33184598 0.68838513]
 [0.58749784 0.00362192 0.50325007 0.54023428 0.96347261]]


In [68]:
# 2x5 random array drawn from standard normal distribution
print(np.random.rand(2, 5))

[[0.0237954  0.17944683 0.47986637 0.70248769 0.07067682]
 [0.99610181 0.15591776 0.2532366  0.02139073 0.99976043]]


In [69]:
# 2x5 random array drawn from a uniform distribution on {0, 1, 2, ..., 9}
print(np.random.randint(10, size=[2, 5]))

[[2 9 1 5 5]
 [5 5 0 0 0]]


##### <span style="color:#0b486b">1.5.1 Random seed</span>


Random numbers generated by computers are not really random. They are called pseudo-random. Thus we can set the random generator to generate the same set of random numbers every time. This is useful while testing the code.

In [72]:
for i in range(5):
    print(np.random.random(), end=' ')

0.27836938509379616 0.4245175907491331 0.8447761323199037 0.004718856190972565 0.12156912078311422 

In [73]:
for i in range(5):
    np.random.seed(100)
    print(np.random.random(), end=' ')

0.5434049417909654 0.5434049417909654 0.5434049417909654 0.5434049417909654 0.5434049417909654 

### <span style="color:#0b486b">1.6 Vectorizing functions</span>


As mentioned earlier in operators, to get a good performance you should avoid looping over elements in an array and use vectorized algorithms. Many methods and functions of NumPy already support vectors, so keep this in mind while writing your own code.

But for now, suppose you have written a step function which does not work with arrays, as the cell below:

In [74]:
def step_func(x):
    """
    scalar implementation of step function
    """
    
    if x>=0:
        return 1
    else:
        return 0

Obviously it fails when dealing with an array, because it expects a scalar as its input. Execute the cell below and see that it raises an error:

In [75]:
# since step_func expects a scalar and recieves an array instead, 
# it raises an error

step_func(np.array([2, 7, -4, -9, 0, 4]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

You can use the function `'np.vectorize()'` to obtain a vectorized version of `'step_func'` that can handle vector data:

In [ ]:
step_func_vectorized = np.vectorize(step_func)
step_func_vectorized(np.array([2, 7, -4, -9, 0, 4]))

Although `'vectorize()'` can automatically derive a vectorized version of a scalar function, but it is always better to keep this in mind and write functions vector-compatilbe, from the beginning. For example we could write the step function as it is shown in the cell below, so it can handle scalar and vector data.

In [ ]:
def step_func2(x):
    """
    vector and scalar implementation of step function
    """
    
    return 1 * (x>=0)

In [ ]:
step_func2(np.array([2, 7, -4, -9, 0, 4]))

## <span style="color:#0b486b">2. Matplotlib</span>


### <span style="color:#0b486b">2.1 What is it?</span>


matplotlib is a python plotting library which produces publication quality figures in a variety of hardcopy formats and interactive environments across platforms. You can generate plots, histograms, power spectra, bar charts, errorcharts, scatterplots, etc, with just a few lines of code. 

For simple plotting the pyplot interface provides a MATLAB-like interface, particularly when combined with IPython. You have full control of line styles, font properties, axes properties, etc, via an object oriented interface or via a set of functions familiar to MATLAB users.

### <span style="color:#0b486b">2.2 Get started</span>


To get started with `'matplotlib'` you can either execute:

In [ ]:
from pylab import *

or

In [ ]:
import matplotlib.pyplot

In fact it is a convention to import it under the name of `'plt'`:

In [ ]:
import matplotlib.pyplot as plt

**note: The second method is preferred.**

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

Regardless of the method you use, it is better to configure matplotlib to embed figures in the notebook instead of opening them in a new window for each figure. To do this use the magic function:

In [ ]:
%matplotlib inline

### 2.3 `plot`

By using `'subplots()'` you have access to both figure and axes objects. 

In [ ]:
x = np.linspace(0, 10)
y = np.sin(x)

In [ ]:
fig, ax = plt.subplots()
ax.plot(x, y)

### <span style="color:#0b486b">2.4 title and labels</span>


In [ ]:
ax.set_title('title here!')
ax.set_xlabel('x')
ax.set_ylabel('sin(x)')
fig

You can also use $\LaTeX$ in title or labels, or change the font size or font family.

In [ ]:
x = np.linspace(-10, 10)
fig, ax = plt.subplots(figsize=(6, 4), dpi=300)
ax.plot(x, x**3-x**2, 'bo', lw=3)

ax.set_title('$x^3-x^2$', fontsize=15)
ax.set_xlabel('$x$', fontsize=15)
ax.set_ylabel('$y$', fontsize=15)

### <span style="color:#0b486b">2.5 Subplots</span>

You can pass the number of subplots to `'subplots()'`. In this case, `'axes'` will be an array that each of its elements associates with one of the subgraphs. You can set properties of each `'ax'` object separately like the cell below. 

Obviously you caould use a loop to iterate over `'axes'`.

In [ ]:
fig, axes = plt.subplots(nrows=1, ncols=2)

x = np.linspace(0, 10)

axes[0].plot(x, np.sin(x))
axes[0].set_xlabel('x')
axes[0].set_ylabel('sin(x)')

axes[1].plot(x, np.cos(x))
axes[1].set_xlabel('xx')
axes[1].set_ylabel('cos(x)')

`'cos(x)'` label is overlapping with the `'sin'` graph. You can adjust the size of the graph or space between the subplots to fix it.

In [ ]:
fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(10, 5))
fig.subplots_adjust(wspace=0.4)
x = np.linspace(0, 10)

axes[0].plot(x, np.sin(x))
axes[0].set_xlabel('x')
axes[0].set_ylabel('sin(x)')

axes[1].plot(x, np.cos(x))
axes[1].set_xlabel('xx')
axes[1].set_ylabel('cos(x)')

### <span style="color:#0b486b">2.6 Legend</span>


In [ ]:
x = np.linspace(0, 10)
fig, ax = plt.subplots(figsize=(7, 5))
ax.plot(x, np.sin(x), label='$sin(x)$')
ax.plot(x, np.cos(x), label='$cos(x)$')
# ax.legend(fontsize=16, loc=3)


### <span style="color:#0b486b">2.7 Customizing ticks</span>


In many cases you want to customize the ticks and their labels on x or y axis. First draw a simple graph and look at the ticks on x-axis. 

In [ ]:
x = np.linspace(0, 10, num=100)

fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(x, np.sin(x), x, np.cos(x), lw=2)

You can change the ticks easily with passing a list (or array) to `'set_xticks()'` or `'set_yticks()'`:

In [ ]:
xticks = [0, 1, 2, 5, 8, 8.5, 10]
ax.set_xticks(xticks)
fig

Or even you can change the labels:

In [ ]:
xticklabels = ['$\gamma$', '$\delta$', 'apple', 'b', '', 'c'] 
ax.set_xticklabels(xticklabels, fontsize=18)
fig

### <span style="color:#0b486b">2.8 Saving figures</span>


In [ ]:
x = np.linspace(0, 10)
fig, ax = plt.subplots(figsize=(7, 5))
ax.plot(x, np.sin(x), label='$sin(x)$')
ax.plot(x, np.cos(x), label='$cos(x)$')
ax.legend(fontsize=16, loc=3)
fig.savefig('myfig.pdf', format='PDF', dpi=300)

### <span style="color:#0b486b">2.9 Other plot styles</span>

There are many other plot types in addition to simple `'plot'` supported by `'matplotlib'`. You will find a complete list of them on [matplotlib gallery](http://matplotlib.org/gallery.html).

#### <span style="color:#0b486b">2.9.1 Scatter plot</span>



In [ ]:
fig, ax = plt.subplots()

x = np.linspace(-0.75, 1., 100)
ax.scatter(x, np.random.randn(x.shape[0]), 
                   s = 250*np.abs(np.random.randn(x.shape[0])), 
                   alpha=0.4,
                  edgecolor='none')
ax.set_title('scatter')

#### <span style="color:#0b486b">2.9.1 Bar plot</span>


In [ ]:
fig, ax = plt.subplots()

x = np.arange(1, 6)
ax.bar(x, x**2, align="center")
ax.set_title('bar')

---
## <span style="color:#0b486b">3. File I/O</span>

### <span style="color:#0b486b">3.1 TXT</span>


TXT file format is the most simplestic way to store data. 

Load a TXT file with `'np.loadtxt()'`:

In [ ]:
x = np.loadtxt("data/txt_data1.txt")
x

Save a TXT file with `'np.savetxt()'`:

In [ ]:
y = np.random.randint(10, size=5)
np.savetxt("data/txt_data2.txt", y)
y

### <span style="color:#0b486b">3.2 CSV</span>



Comma Separated Values format and its variations, are one the most used file format to store data.

You can use `'np.genfromtxt()'` to read a CSV file:
**NOTE:** The best way to read CSV and XLS files is suing **pandas** package that will be introduced later.

In [ ]:
x = np.genfromtxt("data/csv_data1.csv", delimiter=",")
x

Use `'np.savetxt()'` to save a 2d-array in a CSV file.

In [ ]:
x = np.random.randint(10, size=(6,4))
np.savetxt("data/csv_data2.csv", x, delimiter=',')
x

### <span style="color:#0b486b">3.3 JSON</span>


JSON is the most used file format when dealing with web services. 

To read a JSON file, use `'json'` package and `'load()'` function, or `'loads()'` if the data is serialized. It reads the data and parses it into a dictionary.

In [ ]:
import json
with open("data/json_data1.json", 'rb') as fp:
    fcontent = fp.read()
data = json.loads(fcontent)
data.keys()

In [ ]:
data


In [ ]:
data['phoneNumbers']

You can also write a python dictionary into a JSON file. To do this use `'dump()'` or `'dumps()'` functions.

In [ ]:
data = [{'Name': 'Zara', 'Age': 7, 'Class': 'First'}, 
        {'Name': 'Lily', 'Age': 9, 'Class': 'Third'}];
data

In [ ]:
with open("data/json_data_now.json", 'w') as fp:
    json.dump(data, fp)

---
## <span style="color:#0b486b">4. Plotting a histogram</span>


### <span style="color:#0b486b">4.1 Dataset</span>


You are provided with a dataset of percentage of body fat and 10 simple body measurements recoreded for 252 men (courtesy of Journal of Statistics Education - JSE). You can read about this and other [JSE datasets here](http://www.amstat.org/publications/jse/jse_data_archive.htm).

First load the data set into an array:

In [ ]:
import numpy as np

In [ ]:
data = np.genfromtxt("data/fat.dat.txt")
data.shape

Based on the [dataset description](http://www.amstat.org/publications/jse/datasets/fat.txt), 5th column represents the weight in lbs. Index the weight column and call it `'weights'`:

In [ ]:
weights = data[:, 5]
weights

Use array operators to convert the weigts into kg. 1 lb equals to 0.453592 kg.

In [ ]:
a = 3
a = a + 4
a += 4

In [ ]:
weights *= 0.453592
weights = weights.round(2)
weights

### <span style="color:#0b486b">4.2 Histogram</span>


A histogtram is a bar plot that shows you the statistical distribution of the data over a variable. The bars represent the frequency of occurenve by classess of data. We use the package `'matplotlib'` and the function `'hist()'` for plotting the histogram. To learn more about `'matplotlib'` make sure you have read tutorial.

The first line of the cell below if for showing the figure in the notebook and not opening it in a separate window.

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
fig, ax = plt.subplots()
ax.hist(weights)

The `'hist()'` functions automatically group the data over 10 bins. Usually you need to tweek the number of bins to obtain a more expressive histogram.

In [ ]:
fig, ax = plt.subplots(figsize=(7, 5))
ax.hist(weights, bins=20)
# title
# label

### <span style="color:#0b486b">4.3 Boxplot</span>

A `Boxplot` is a convenient way to graphically display numerical data. 

In [ ]:
import matplotlib
fig, ax = matplotlib.pyplot.subplots(figsize=(7, 5))
matplotlib.rcParams.update({'font.size': 14})
ax.boxplot(weights, 0, labels=['group1'])
ax.set_ylabel('weight (kg)', fontsize=16)
ax.set_title('Weights BoxPlot', fontsize=16)